MONGODB_CONFIG:
  name: 'ignition_test' # 自定义次数据库链接名称
  type: mongodb # 数据库链接类型
  url: 'mongodb://root:123456@47.99.147.11:27017/gateway?authSource=admin' # 数据库链接地址
  username: 'root' # 数据库链接用户名
  password: '123456' # 数据库链接密码
  database: 'fast_gateway_test' # 数据库名
  entities: 'mongo' # 自定义加载类型
  logging: false # 数据库打印日志
  synchronize: true # 是否开启同步数据表功能
MYSQL_CONFIG:
  name: 'material_test'
  type: 'mysql'
  host: '47.99.147.11'
  port: 3306
  username: 'root'
  password: '123456'
  database: 'material_test'
  entities: 'mysql'
  logging: true
  synchronize: true
